- import_tasks: CentOS.yml
  when: ansible_distribution == 'CentOS'

- import_tasks: Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'


- name: Change MariaDB root user password 
  mysql_user: 
    name: root 
    host: '{{item}}'
    password: "{{mariadb_password}}"
  with_items: 
    - 127.0.0.1
    - ::1
    - localhost
  ignore_errors: yes

- name: Removes all anyelse user accounts
  mysql_user:
    login_user: root
    login_password: "{{mariadb_password}}"
    name: ''
    host_all: yes
    state: absent

- name: Remove hostname user accounts
  mysql_user: login_user=root login_password={{mariadb_password}} name='root' host={{ ansible_nodename }} state=absent

- name: Removes test Databases
  mysql_db:
    login_user: root
    login_password: "{{mariadb_password}}"
    name: test
    state: absent

- name: Removing privileges on test database
  command: mysql -uroot -p{{mariadb_password}} -e "DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'"


- name: Create DB
  mysql_db:
    login_user: root
    login_password: '{{mysql_password}}'
    name: "{{app_db}}"
  when: (app_db != none) and (app_db is defined)

- name: Create User
  mysql_user:
    login_user: root
    login_password: '{{mysql_password}}'
    name: "{{app_db_user}}"
    password: "{{app_db_password}}"
    host: "{{app_db_host}}"
    priv: '{{app_db}}.*:ALL,GRANT'
  when: (app_db_user != none) and (app_db_host != none) and (app_db != none) and (app_db_user is defined) and (app_db_host is defined) and (app_db is defined)and (app_db_password != none) and (app_db_password is defined)





- name: Create credentials Folder
  file:
    path: /credentials
    state: directory

- name: Write Databases Password
  template:
    src: password.txt.jinja2
    dest: /credentials/password.txt
    mode: 644

- name: Check MySQL Version
  shell: mysql -V
  register: mysql_ver
  notify: MariaDB Version