- name: Init for azure
  shell: waagent -deprovision+user --force
  when: cloud == "azure"
  ignore_errors: yes

- name: Remove SSH info
  file: 
    path: '{{item}}'
    state: absent
  with_items:
    - /home/{{admin_username}}/.ssh
    - /root/.ssh
    - /home/frapper/.ssh
  when: cloud == "none"
