- block:
  - name: ResourceDisk EnableSwap
    lineinfile:
        dest: /etc/waagent.conf
        regexp: 'ResourceDisk.EnableSwap=n'
        line: "ResourceDisk.EnableSwap=y"
        state: present

  - name: ResourceDisk SwapSizeMB
    lineinfile:
        dest: /etc/waagent.conf
        regexp: 'ResourceDisk.SwapSizeMB=0'
        line: "ResourceDisk.SwapSizeMB=2048"
        state: present

  - name: Init for azure
    shell: waagent -deprovision+user --force
    
  when: cloud == "azure"

- name: Remove SSH info
  file: 
    path: '{{item}}'
    state: absent
  with_items:
    - /home/{{admin_username}}/.ssh
    - /root/.ssh
    - /home/frapper/.ssh
  when: cloud == "none"
